- name: Set up Maven Central Repository
  uses: actions/setup-java@v4
  with:
    java-version: '21'
    distribution: 'temurin'
    server-id: ossrh  # Must match the <id> in pom.xml's distributionManagement
    server-username: ${{ secrets.OSSRH_USERNAME }}
    server-password: ${{ secrets.OSSRH_TOKEN }}

# Add this step to create settings.xml
- name: Configure Maven settings.xml
  run: |
    mkdir -p ~/.m2
    cat > ~/.m2/settings.xml <<EOF
    <settings>
      <servers>
        <server>
          <id>ossrh</id>
          <username>${{ secrets.OSSRH_USERNAME }}</username>
          <password>${{ secrets.OSSRH_TOKEN }}</password>
        </server>
      </servers>
    </settings>
    EOF